[build]
builder = "nixpacks"
buildCommand = "npm install && npm run install-backend && npm run install-frontend && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
node_version = "18" 